  - hosts: monitoring
    tasks:
    - name: 'Send notification message via Slack'
      slack:
        token: 'thetoken/generatedby/slack'
        msg: 'Ansible task finished {{ inventory_hostname }}'
      delegate_to: localhost
