- hosts: monitoring
  tasks:
  - name: 'Send notification message via Telegram'
    telegram:
      token: 'bot9999999:XXXXXXXXXXXXXXXXXXXXXXX'
      chat_id: "@channel_name"
      msg: 'Ansible task finished {{ inventory_hostname }}'
