- hosts: monitoring
  tasks:
  - name: Download gitlab repo
    get_url: url=https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh dest=/usr/src/gitlab.rpm.sh mode=0755 validate_certs=no
    when: ansible_os_family == "RedHat"
  - name: Install gitlab repo
    shell: /usr/src/gitlab.rpm.sh
    when: ansible_os_family == "RedHat"
  - name: Install gitlab
    yum: name=gitlab-ce state=latest
    notify: configure gitlab
    when: ansible_os_family == "RedHat"
  - name: Start the Grafana service
    service:
        name: gitlab-ce
        state: restarted
        enabled: yes
