- hosts: localhost
  tasks:
    - name: Import InfluxDB GPG signing key
      apt_key: url=https://repos.influxdata.com/influxdb.key state=present
    - name: Add source
      shell: . /etc/lsb-release
      args:
        executable: /bin/bash
      tags: [ source ]
    - name: Add Kapacitor repository
      apt_repository: repo='deb https://repos.influxdata.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable'
        state=present
      become: yes
      tags: [ apt ]
    - name: Install Kapacitor packages
      apt:
        update_cache=yes
        name=kapacitor
        state=present
      become: yes
      tags: [ installation ]
    - name: Creating the Configuration File
      shell: 'kapacitord config'
    - name: Start the Kapacitor service
      systemd:
        name=kapacitor
        state=restarted
