- hosts: localhost
  tasks:
    - name: Add Atom ppa
      become: yes
      apt_repository:
        repo: 'ppa:webupd8team/atom'
    - name: Install Atom
      become: yes
      apt:
        name: atom
        state: present
    - name: Add packages
      shell: "apm list --bare | grep -E '^{{ item }}@'&& echo 'Already installed.' || apm install '{{ item }}'"
      with_items:
        - atom-beautify
        - busy-signal
        - intentions
        - linter
        - linter-pycodestyle
        - linter-pylama
        - linter-pylint
        - linter-shellcheck
        - linter-ui-default
        - markdown-preview-plus
        - minimap
        - python-autopep8
        - script
        - split-diff
        - tree-view-git-branch
      register: apm_result
      changed_when: "'Already installed.' not in apm_result.stdout"
