- hosts: localhost
  tasks:
    - name: Add Atom ppa
      become: yes
      apt_repository:
        repo: 'ppa:webupd8team/atom'
    - name: Install Atom
      become: yes
      apt:
        name: atom
        state: present
    - name: Add packages
      shell: "apm list --bare | grep -E '^{{ item }}@'&& echo 'Already installed.' || apm install '{{ item }}'"
      with_items:
        - atom-make
        - python-indent
        - autocomplete-ansible
        - autocomplete-clang
        - autocomplete-python
        - clang-format
        - linter
        - linter-clang
        - linter-pylint
        - linter-shellcheck
        - linter-python
        - markdown-preview-plus
        - markdown-writer
        - minimap
        - python-indent
        - python-autopep8
        - python-iresolve
        - python-nosetests
        - python-tools
        - atom-python-run
        - script
        - split-diff
        - svg-preview
        - tree-view-git-branch
      register: apm_result
      changed_when: "'Already installed.' not in apm_result.stdout"
