- hosts: localhost
  tasks:
    - name: Import InfluxDB GPG signing key
      apt_key:
        url: https://repos.influxdata.com/influxdb.key state=present
    - name: Add source
      shell: . /etc/lsb-release
      args:
        executable: /bin/bash
      tags: [ source ]
    - name: Add InfluxDB repository
      apt_repository:
        repo: 'deb https://repos.influxdata.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable'
        state: present
      become: yes
      tags: [ apt ]
    - name: Install InfluxDB packages
      apt:
        update_cache: yes
        name: influxdb
        state: present
      become: yes
      tags: [ installation ]
    - name: Start the InfluxDB service
      service:
        name: influxdb
        state: restarted
    - name: influxdb - wait for service
      wait_for:
        port: 8086
        delay: 1
    - name: Creating a database
      shell: "influx --execute 'CREATE DATABASE mydb'"
      args:
        executable: /bin/bash
      tags: [ create db ]
    - name: Writing data
      shell: "influx --execute 'INSERT cpu,host=serverA,region=us_west value=0.75' -database='mydb'"
      tags: [ write db ]
