- hosts: localhost
  tasks:
    - name: Add InfluxDB repository
      apt_repository: repo='deb https://repos.influxdata.com/ubuntu yakkety stable' state=present
    - name: Install InfluxDB packages
      apt: name=influxdb state=present
    - name: Install influxdb-client
      apt: name=influxdb-client state=present
    - name: Start the InfluxDB service
      service: name=influxdb state=restarted
    - name: influxdb - wait for service
      wait_for: port=8086 delay=2
    - name: Create sample database
      command: /usr/bin/influx -execute 'CREATE DATABASE sample_database'
      ignore_errors: yes
    - name: Load some test data into sample database
      uri:
        url: http://localhost:8086/write?db=sample_database
        method: POST
        body: "random_ints,host=server_{{ 10 | random }} value={{ 100 | random }}"
        status_code: 204
      with_sequence: start=1 end=10
