- hosts: monitoring
  tasks:
    - name: Add repository
      yum_repository:
        name: influxdb
        description: InfluxDB Repository - RHEL $releasever
        baseurl: https://repos.influxdata.com/rhel/\$releasever/\$basearch/stable
        enabled: yes
        gpgkey: https://repos.influxdata.com/influxdb.key
        gpgcheck: yes
    - name: Install influxdb packages
      yum:
          name: influxdb
          state: present
          update_cache: yes
    - name: Start the influxdb service
      service:
          name: influxdb
          state: restarted
       
