- hosts: monitoring
  tasks:
    - name: Add repository
      yum_repository:
        name: influxdb
        description: InfluxDB Repository - RHEL $releasever
        baseurl: https://repos.influxdata.com/rhel/\$releasever/\$basearch/stable
        enabled: yes
        gpgkey: https://repos.influxdata.com/influxdb.key
        gpgcheck: yes
    - name: Install influxdb packages
      yum:
          name: influxdb
          state: present
          update_cache: yes
    - name: Start the influxdb service
      service:
          name: influxdb
          state: restarted
    - name: influxdb - wait for service
      wait_for:
        port: 8086
        delay: 1
    - name: Creating a database
      shell: "influx --execute 'CREATE DATABASE mydb'"
      args:
        executable: /bin/bash
      tags: [ create db ]
    - name: Writing data
      shell: "influx --execute 'INSERT cpu,host=serverA,region=us_west value=0.75' -database='mydb'"
      tags: [ write db ]
