- hosts: localhost
  tasks:
    - name: Install tools
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - python3
        - ipython3
        - python3-pip
