- hosts: localhost
  tasks:
    - name: Install tools
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - python3
        - ipython3
        - python3-pip
        - vim
        - qemu-kvm 
        - libvirt-bin 
        - ubuntu-vm-builder 
        - bridge-utils
        - virt-manager
        - sshpass
        - shellcheck
        - ssh
        - ethtool
        - unrar
        - gimp
        - wireshark
